# Generated by Django 4.2 on 2023-05-23 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_remove_note_content_remove_note_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='id_time_favorito',
            new_name='id_time',
        ),
    ]
